function response = query(addr, varargin)
    opt = weboptions('MediaType',   'application/edn', ...
                     'ContentType', 'json');
    response = webwrite(addr, ...
                        sprintf(varargin{1}, varargin{2:end}),...
                        opt);
end